name: istio-envoy-arm64-build-env

on:
  push:
    branch: master
    paths:
      - '.github/workflows/istio-envoy-arm64-build-env.yml'
      - 'build-env/**'

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - run: make -e TAG=$(cat ./build-env/.version) build-build-env